language: node_js
node_js:
- 11.7.0
branches:
  only:
  - source

install: npm install

before_script:
- git config --global user.name __GIT_USENAME__
- git config --global user.email __GIT_EMAIL__
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build